### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by dpanic** [calebzulawski/symbol-slasher#14]
Hey,

I tried this on Android .so files.

When I run APK I get this error:
```E/linker: "!/lib/arm64-v8a/libgojni.so" has invalid shdr offset/size: 14146606/2624```

Did you had such problems?

**Comment by calebzulawski** [comment]
I've never tried it on Android objects but I wouldn't expect them to be any different.  Maybe there's a bug in this version of the object parser?

**Comment by dpanic** [comment]
I saw exactly the same error in UPX.

https://github.com/upx/upx/issues/242

When you set ```--android-shlib``` in UPX it works...I did quick look on their source code, and indeed it needs to work differently on different architectures.

ARM 32bit, ARM 64bit...

**Comment by dpanic** [comment]
Update:

If I disable ```object->remove(object->static_symbols_section(), true);``` in file **store.h** all works perfectly!

Is this okay to do?

**Comment by calebzulawski** [comment]
In that case, can you try running it with `--keep-static`?

**Comment by dpanic** [comment]
> In that case, can you try running it with `--keep-static`?

That should work. I will try it tomorrow.

**Comment by dpanic** [comment]
One more question, is hashing process inreversible if there is no symbols.json file?

I checked source code, looks like it is inreversible.

**Comment by calebzulawski** [comment]
Yes, the intention is that it is not reversible.
